### ISSUE TITLE
mateo-bridge is not working with empty storage variables as result

### ISSUE THREAD

**Issue by mschulte** [viadee/mateo-camunda-bridge#4]
if we have an empty-string as storage variable, our bridge is throwing a bpmn-error instead of returning that empty-string as result to the process. 

any specific reasons for that? does not feel like the supposed-to-be natural behaviour?

**Comment by Marcel2906** [comment]
This is due to the configuration of mateo. Mateo does not distinguish between not found variables and empty variables. I first solved it in the mateo Camunda Bridge by returning not found variables as an empty string.
